FROM node:22-alpine

WORKDIR /opt/app

# Copy package files and install dependencies
COPY package.json package-lock.json* ./
RUN npm config set registry http://registry.npmjs.org/
RUN npm install --verbose --strict-ssl=false


# Copy the rest of the application
COPY . .

EXPOSE 3000

# Run in development mode (Turbopack is default in Next.js 15)
CMD ["npm", "run", "dev"]
